# Generated by Django 6.0.1 on 2026-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Име на търсенето')),
                ('url', models.URLField(verbose_name='Линк за следене')),
                ('category', models.CharField(choices=[('car', 'Car'), ('job', 'Job')], max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Търсене',
                'verbose_name_plural': 'Търсения',
            },
        ),
    ]
