# Generated by Django 6.0.1 on 2026-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка (за авто-попълване)'),
        ),
        migrations.AddField(
            model_name='search',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модел (за авто-попълване)'),
        ),
    ]
