# Generated by Django 6.0.1 on 2026-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_search_brand_search_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заглавие'),
        ),
    ]
