# Generated by Django 6.0.1 on 2026-06-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='is_initial_scan_done',
            field=models.BooleanField(default=False),
        ),
    ]
