# Generated by Django 6.0.1 on 2026-06-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_search_is_initial_scan_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Дата на записа')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.listing')),
            ],
            options={
                'verbose_name': 'История на цената',
                'verbose_name_plural': 'История на цените',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
