# Generated by Django 6.0.1 on 2026-06-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.search'),
        ),
    ]
