# Generated by Django 6.0.1 on 2026-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='На пауза'),
        ),
    ]
