# Generated by Django 6.0.1 on 2026-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_search_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
