# Generated by Django 6.0.1 on 2026-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_carlisting_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
